### ISSUE TITLE
website TOC: Links don't point to right location

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/translationAcademy#41]
Examples: 
- [x] Translation Manual Vol 1 / Figures of Speech
- [x] Translation Manual Vol 1 / Grammar / Word Order
- [x] Translation Manual Vol 2 / Grammar / Active or Passive
- [x] Translation Manual Vol 2 / Grammar / Speech Quotations
- [x] Translation Manual Vol 2 / Pronouns / Exclusive
- [x] Technology Manual Vol 1 / uW Mobile App / Language Information
- [x] Audio Manual / Introduction
- [x] Audio Manual / Recording
- [x] Audio Manual / Distribution / License
- [x] Audio Manual / Recommended Equipment / Audio Interfaces
- [x] Audio Manual / Recommended Equipment / Playback Monitoring

**Comment by phillip-hopper** [comment]
Use ref to generate the id instead of the title.
